name: keyboard
description: Application that emulates a piano keyboard with MIDI controller support
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
homepage: https://github.com/roemvaar/keyboard

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_midi: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/sf2/Piano.sf2
